INCLDIR = ./include
CC = gcc
CFLAGS = -O2
CFLAGS += -I$(INCLDIR)

OBJDIR = obj

_DEPS = task2.h
DEPS = $(patsubst %,$(INCLDIR)/%,$(_DEPS))

_OBJS = task2.o task2_fib.o task2_prim.o task2_kvad.o task2_cube.o \
        task2_perf.o task2_abun.o task2_def.o task2_odd.o
OBJS = $(patsubst %,$(OBJDIR)/%,$(_OBJS))

$(OBJDIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)
   
task2: $(OBJS)
	gcc -o $@ $^ $(CFLAGS) -lm   #lagt til -lm for bruk av <math.h>
   
.PHONY: clean
clean:
	rm -f $(OBJDIR)/*.o *~ core $(INCLDIR)/

